name: Pack and Deploy

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - uses: actions/checkout@v4

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v4
      with:
        node-version: 22.x

    - name: Build
      run: |
        npm install
        npx webpack

    - name: UploadBundle
      uses: actions/upload-artifact@v4
      with:
        name: RendererBundle
        path: ${{ github.workspace }}/renderer_out/

    - name: Upload Index
      uses: actions/upload-artifact@v4
      with:
        name: BundleIndex
        path: ${{ github.workspace }}/testBundle.html

    - name: Upload CSS
      uses: actions/upload-artifact@v4
      with:
        name: BundleCSS
        path: ${{ github.workspace }}/fileHTML.css

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Get Artifact
      uses: actions/download-artifact@v4
      with:
        name: RendererBundle
        path: ${{ github.workspace }}/uptorepo/

    - name: Get Index
      uses: actions/download-artifact@v4
      with:
        name: BundleIndex
        path: ${{ github.workspace }}/uptorepo/

    - name: Get CSS
      uses: actions/download-artifact@v4
      with:
        name: BundleCSS
        path: ${{ github.workspace }}/uptorepo/

    - name: Publish Artifact
      uses: actions/upload-pages-artifact@v3
      with:
        path: ${{ github.workspace }}/uptorepo/

    - name: Deploy to Pages
      uses: actions/deploy-pages@v4